blueprints/manage_events.py
from flask import Blueprint, request, redirect, url_for, flash
from flask_login import current_user
from models.User import User
from models.Event import Event, TimeSlot
from db import db
import arrow
from brain import get_acceptee_events, find_free_times, filter_by_duration
from datetime import datetime,timedelta
manage_events = Blueprint('manage_events', __name__,
                        template_folder='templates')
@manage_events.route("/add-event", methods=["POST"])
def add_event():
    event_name = request.form.get('event_name')
    date_times = request.form.get('datetimes')
    hours = int(request.form.get('hours'))
    minutes = int(request.form.get('minutes'))
    
    start_after = arrow.get(request.form.get('startafter'), 'HH:mm')
    end_before = arrow.get(request.form.get('endbefore'), 'HH:mm')

    invitees = request.form.getlist('users[]')

    invitees = [User.query.filter_by(id=int(invitee)).first() for invitee in invitees]
    

    # Split the string into two parts using the ' - ' delimiter
    first_date, last_date = date_times.split(" - ")

    # Define the date format
    date_format = "%m/%d/%y %I:%M %p"

    # Parse the start and end times
    first_date = datetime.strptime(first_date, date_format)
    last_date = datetime.strptime(last_date, date_format)
    event = Event(current_user,event_name, hours, minutes, first_date, last_date, start_after, end_before, invitees) 
    db.session.add(event)
    db.session.commit()
    flash("Event added")
    return redirect("/")

@manage_events.route('/accept_event/<int:event_id>', methods=['POST'])
def accept_event(event_id):
    event = Event.query.filter_by(id=event_id).first()
    if event:
        current_user.invited_events.remove(event)
        current_user.accepted_events.append(event)
        db.session.commit()
    return redirect(url_for('index'))

@manage_events.route('/decline_event/<int:event_id>', methods=['POST'])
def decline_event(event_id):
    event = Event.query.filter_by(id=event_id).first()
    if event:
        current_user.invited_events.remove(event)
        current_user.declined_events.append(event)
        db.session.commit()
    return redirect(url_for('index'))

@manage_events.route('/solve-event', methods=['POST'])
def solve_event():
    event_id= request.form.get("event_id")
    event = Event.query.filter_by(id=event_id).first()
    acceptee_events = get_acceptee_events(event)
    free_times = find_free_times(acceptee_events, event.start_after, event.end_before)
    long_enough = filter_by_duration(free_times, timedelta(hours=event.hours, minutes=event.minutes))
    event.time_slots = []
    for slot in long_enough:
        start_time, end_time = slot
        slot = TimeSlot(start_time=start_time.datetime, end_time=end_time.datetime)
        event.time_slots.append(slot)
        db.session.add(slot)

    db.session.commit()
    return redirect("/")
@manage_events.route('/delete-event', methods=['POST'])
def delete_caldav():
    event_id = request.form.get('event_id')
    event = Event.query.filter_by(id=event_id).first()
    db.session.delete(event)
    db.session.commit()
    flash(f"Deleted event: {event.name}")
    return redirect("/")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
  <title>Freetime Finder</title>
  {% block head %}{% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Freetime Finder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Hi, {{current_user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/logout">Logout</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container mt-5">
    <div class="row">
      {% with messages = get_flashed_messages() %} {% if messages %} {% for
      message in messages %}
      <div class="w-100 mx-3 alert alert-primary" role="alert">
        {{message}}
      </div>
      {% endfor %} {% endif %} {% endwith %}
    </div>
  </div>
  {% block content %} {% endblock %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends "base.html" %}{%block head%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@6.1.9/index.global.min.js"></script>

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js" defer></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{%endblock%} {% block content %}
<!-- Modal HTML -->
<div class="modal" id="newUserModal" tabindex="-1" aria-labelledby="newUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newUserModalLabel">
          Welcome to Freetime Finder
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Before you get started, a couple disclaimers</p>
        <h3 class="text-warning">This is alpha quality software</h3>
        <p>
          That's programmer speak for "this will break if you look at it wrong".
          Don't panic if something doesn't work. Don't trust this software to be
          particularly reliable, accurate, or any similar confidence-inspiring
          adjectives.
        </p>
        <h3 class="text-warning">This will give me access to your calendar</h3>
        <p>
          I'm not going to go poking around through your stuff, but by adding
          your information you are giving me full read access to your calendar.
          If you use caldav, I can also see your username and password, and
          probably modify your calendars. Again, I won't. I have no interest in
          doing so. But, you should know that this site has minimal privacy
          protections
        </p>
      </div>
    </div>
  </div>
</div>
<div class="container">
  {% for event in current_user.invited_events %}
  <div class="w-100 alert alert-success d-flex justify-content-between align-items-center" role="alert">
    <span>You've been invited to {{ event.name }}</span>
    <div>
      <form action="{{ url_for('manage_events.accept_event', event_id=event.id) }}" method="post" class="d-inline">
        <button type="submit" class="btn btn-success btn-sm">
          Accept <i class="bi bi-check"></i>
        </button>
      </form>
      <form action="{{ url_for('manage_events.decline_event', event_id=event.id) }}" method="post" class="d-inline">
        <button type="submit" class="btn btn-danger btn-sm">
          Decline <i class="bi bi-x"></i>
        </button>
      </form>
    </div>
  </div>
  {% endfor %}

  <div class="row">
    <div class="col-md-4 mb-3">
      <div class="card p-2">
        <h2>Calendars</h2>
        <div class="mt-1">
          <h4>Web Calendars</h4>
          <ul class="list-group">
            {% for webcal in current_user.webcals %}
            <li class="list-group-item d-flex justify-content-between align-items-center" style="word-break: break-all">
              {{ webcal.url }}
              <form action="/delete-webcal" method="POST">
                <input type="hidden" name="webcal_id" value="{{ webcal.id }}" />
                <button type="submit" class="btn btn-danger btn-sm">
                  <i class="bi bi-trash"></i>
                </button>
              </form>
            </li>
            {% endfor %}
          </ul>

          <h5>Add Web Calendar</h5>
          <form action="/add-webcal" method="POST">
            <input class="form-control" type="url" name="calendar" id="calendar" />
            <div class="d-flex mt-1 justify-content-end">
              <input class="ms-auto d-block btn btn-primary" type="submit" value="Add" />
            </div>
          </form>
        </div>
        <div class="mt-2">
          <h4>Calendar Files</h4>
          <ul class="list-group">
            {% for calfile in current_user.calfiles %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              {{ calfile.get_name() }}
              <form action="/delete-calfile" method="POST">
                <input type="hidden" name="calfile_id" value="{{ calfile.id }}" />
                <button type="submit" class="btn btn-danger btn-sm">
                  <i class="bi bi-trash"></i>
                </button>
              </form>
            </li>
            {% endfor %}
          </ul>
          <h5>Upload a Calendar</h5>
          <form action="/add-calfile" method="post" enctype="multipart/form-data">
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="calfile" accept="text/calendar" id="inputGroupFile01"
                onchange="(event)=>{console.log('hi')}" />
              <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
            </div>
            <div class="d-flex mt-1 justify-content-end">
              <input class="ms-auto d-block btn btn-primary" type="submit" value="Add" />
            </div>
          </form>
        </div>
        <div class="mt-2">
          <h4>Caldav Accounts</h4>
          {% for credential in current_user.caldav_credentials %}
          <li class="list-group-item d-flex flex-row align-items-start">
            <div class="credential-info">
              <span class="credential-url">{{ credential.url }}</span>
              <span class="badge badge-primary">{{ credential.username }}</span>
            </div>
            <form action="/delete-caldav-credential" method="POST">
              <input type="hidden" name="caldav_id" value="{{ credential.id }}" />
              <button type="submit" class="btn btn-danger btn-sm">
                <i class="bi bi-trash"></i>
              </button>
            </form>
          </li>
          {% endfor %}

          <h5>Add Caldav Account</h5>
          <form action="/add-caldav" method="post">
            <input class="form-control" type="url" name="url" id="url" placeholder="URL" />
            <input class="mt-3 form-control" type="username" name="username" id="username" placeholder="Username" />
            <input class="mt-3 form-control" type="password" name="password" id="password" placeholder="Password" />
            <div class="d-flex mt-1 justify-content-end">
              <input class="ms-auto d-block btn btn-primary" type="submit" value="Add" />
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <ul class="list-group">
        {%for event in current_user.created_events%}
        <li class="my-1 list-group-item d-flex justify-content-between align-items-center">
          <div class="d-flex flex-column">
            <div>
              <strong>{{ event.name }}</strong> {% for user in event.accepted_users %}
              <span class="badge badge-success">{{ user.username }}</span>
              {% endfor %} {% for user in event.invited_users %}
              <span class="badge badge-secondary">{{ user.username }}</span>
              {% endfor %} {% for user in event.declined_users %}
              <span class="badge badge-danger">{{ user.username }}</span>
              {% endfor %}
              <hr class="my-1">
              <ul> {% for slot in event.time_slots %}
                {% if event.time_slots[loop.index - 2].start_time.strftime("%d") != slot.start_time.strftime("%d") %}
              </ul>
              <strong>{{ slot.start_time.strftime("%A %m/%d") }}</strong>
              <ul>
                {% endif %}
                <li>{{ slot.start_time.strftime("%I:%M %p") }} - {{ slot.end_time.strftime("%I:%M %p") }}</li>
                {% endfor %}
            </div>


          </div>
          <div class="d-flex d-flex-row">
            <form class="pl-1" action="/solve-event" method="POST">
              <input type="hidden" name="event_id" value="{{ event.id }}" />
              <button type="submit" class="btn btn-primary btn-sm">
                <i class="bi bi-calendar-check"></i> Find
              </button>
            </form>
            <form class="pl-1" action="/delete-event" method="POST">
              <input type="hidden" name="event_id" value="{{ event.id }}" />
              <button type="submit" class="btn btn-danger btn-sm">
                <i class="bi bi-trash"></i>
              </button>
            </form>
          </div>
        </li>

        {%endfor%} {%for event in current_user.accepted_events%} {%if
        event.creator != current_user %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="d-flex flex-column">
            <div>
              {{ event.name }} {% for user in event.accepted_users %}
              <span class="badge badge-success">{{ user.username }}</span>
              {% endfor %} {% for user in event.invited_users %}
              <span class="badge badge-secondary">{{ user.username }}</span>
              {% endfor %} {% for user in event.declined_users %}
              <span class="badge badge-danger">{{ user.username }}</span>
              {% endfor %}
            </div>
            <ul>
              {%for slot in event.time_slots%}
              <li>
                {{slot.start_time.strftime('%m/%d/%y %I:%M %p')}} -
                {{slot.end_time.strftime('%m/%d/%y %I:%M %p')}}
              </li>
              {%endfor%}
            </ul>
          </div>
          <div class="d-flex d-flex-row">
            <form class="pl-1" action="/solve-event" method="POST">
              <input type="hidden" name="event_id" value="{{ event.id }}" />
              <button type="submit" class="btn btn-primary btn-sm">
                <i class="bi bi-calendar-check"></i> Find
              </button>
            </form>
          </div>
        </li>
        {%endif%} {%endfor%}
      </ul>

      <!--<div id="fullcalendar"></div>-->
      <div class="card p-3">
        <h2>Create New Event</h2>
        <form action="/add-event" method="POST">
          <h5 class="mt-2">Event Name</h5>
          <input type="text" class="form-control" name="event_name" />
          <h5 class="mt-2">Duration</h5>
          <div class="form-row align-items-center">
            <div class="col-auto">
              <label class="my-auto" for="hours">Hours</label>
              <input type="number" name="hours" id="hours" value="0" class="form-control" />
            </div>
            <div class="col-auto">
              <label class="my-auto" for="minutes">Minutes</label>
              <input type="number" name="minutes" id="minutes" value="0" class="form-control" />
            </div>
          </div>
          <h5 class="mt-2">Date Range</h5>
          <input type="text" name="datetimes" class="form-control" />
          <h5 class="mt-2">Invitees</h5>
          <select class="js-example-basic-multiple w-100" name="users[]" multiple="multiple">
            {% for user in users %}
            <option value="{{user.id}}">{{user.username}}</option>
            {% endfor %}
          </select>
          <em>Invitees will not be notified, please contact them directly</em>
          <div class="d-flex mt-1 justify-content-end">
            <input class="ms-auto d-block btn btn-primary" type="submit" value="Invite" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    console.log("This ran");
    var calendarEl = document.getElementById("fullcalendar");
    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialView: "dayGridMonth",
      initialDate: "2023-09-07",
      height: "60vh",
      headerToolbar: {
        left: "prev,next today",
        center: "title",
        right: "dayGridMonth",
      },
    });

    calendar.render();
  });
  $(document).ready(function () {
    $(".js-example-basic-multiple").select2();
    // Check if the ?newuser parameter is set in the URL
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.has("newuser")) {
      // If the parameter is present, show the modal
      $("#newUserModal").modal("show");
    }
  });
  $(function () {
    $('input[name="datetimes"]').daterangepicker({
      //timePicker: true,
      startDate: moment().startOf("hour"),
      endDate: moment().startOf("hour").add(32, "hour"),
      locale: {
        format: "M/DD/YY hh:mm A",
      },
    });
  });
</script>
{% endblock %}

templates/login.html
{% extends "base.html" %} {% block content %}

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Login</div>
        <div class="card-body">
          <form method="POST">
            <div class="mb-3">
              <label for="username" class="form-label text-secondary"
                >Username</label
              >
              <input
                type="text"
                class="form-control"
                id="username"
                name="username"
              />
            </div>
            <div class="mb-3">
              <label for="password" class="form-label text-secondary"
                >Password</label
              >
              <input
                type="password"
                class="form-control"
                id="password"
                name="password"
              />
            </div>
            <button type="submit" class="btn btn-primary mx-auto w-100">
              Login
            </button>
            <div class="text-secondary pt-2">
              <a href="/signup" class="text-secondary">Sign up</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %} {% block content %}
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@6.1.9/index.global.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    console.log("This ran");
    var calendarEl = document.getElementById("fullcalendar");
    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialView: "dayGridMonth",
      initialDate: "2023-09-07",
      height: "60vh",
      headerToolbar: {
        left: "prev,next today",
        center: "title",
        right: "dayGridMonth",
      },
    });

    calendar.render();
  });
</script>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Sign Up</div>
        <div class="card-body">
          <form method="POST">
            <div class="mb-3">
              <label for="username" class="form-label text-secondary"
                >Username</label
              >
              <input
                type="text"
                class="form-control"
                id="username"
                name="username"
              />
            </div>
            <div class="mb-3">
              <label for="password" class="form-label text-secondary"
                >Password</label
              >
              <input
                type="password"
                class="form-control"
                id="password"
                name="password"
              />
            </div>
            <div class="mb-3">
              <label for="confirm-password" class="form-label text-secondary"
                >Confirm Password</label
              >
              <input
                type="password"
                class="form-control"
                name="confirm-password"
                id="confirm-password"
              />
            </div>
            <div class="mb-3">
              <label for="captcha" class="form-label text-secondary"
                >Robot Test</label
              >
              <input
                type="text"
                class="form-control"
                name="captcha"
                id="captcha"
              />
              <small id="emailHelp" class="form-text text-muted"
                >To prove you aren't a robot: Please type the name of the saint
                the gregorian calendar is named after.</small
              >
            </div>

            <button type="submit" class="btn btn-primary mx-auto w-100">
              Sign Up
            </button>
            <div class="text-secondary pt-2">
              <a href="/login" class="text-secondary">Login</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}